baseURL = "https://www.f4egm.ovh/"
languageCode = "fr-fr"
title = "Radio&Tech - F4EGM"
theme = "PaperMod"

[params]
  ShowToc = true
  TocOpen = true
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowSearch = true
  ShowPostImage = true
  customCSS = ["css/extended/custom.css"]
  layout = "grid"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
  
  [menu]
  [[menu.main]]
    name = "Antennes"
    url = "/posts/antennes/"
    weight = 10

  [[menu.main]]
    name = "SDR"
    url = "/posts/sdr/"
    weight = 20

  [[menu.main]]
    name = "Electronique"
    url = "/posts/electronique/"
    weight = 30

  [[menu.main]]
    name = "Mecanique"
    url = "/posts/mecanique/"
    weight = 40

  [[menu.main]]
    name = "Logiciels"
    url = "/posts/logiciels/"
    weight = 50

  [[menu.main]]
    name = "BlaBla"
    url = "/posts/BlaBla/"
    weight = 60

  [[menu.main]]
    name = "Domotique"
    url = "/posts/Domotique/"
    weight = 70
	
  [[menu.main]]
    name = "Technique Propag Calculs"
    url = "/posts/TechPropagCalc/"
    weight = 80

  [[menu.main]]
    name = "Satellites"
    url = "/posts/satellites/"
    weight = 90
		
  [[menu.main]]
    name = "Associations"
    url = "/posts/Associations/"
    weight = 100
	
	
